### ISSUE TITLE
Script not working

### ISSUE THREAD

**Issue by prvnkumark** [nccgroup/cisco-SNMP-enumeration#1]
Hi,

It seems very useful script , however its not working for me.

I have tested host with snmp known community public string it fails to bruteforce, not sure where its missing from wireshark i can see its trying public string however this script fails.

**Comment by olliencc** [comment]
Resolved in 5dbcc233a193e7f79a1a96c13d24441fcbb675ce and 441029989c856c6b51625fdba706d986917c52fc  by Tom Watson of NCC Group
